### ISSUE TITLE
Cleanup 'examples/traffic_light_arduino'

### ISSUE THREAD

**Issue by jdicks** [Yakindu/examples#1]
as e.g. .elf is a binary format it isn't compareable well and mostly marked as changed when using git/eGit. in some circumstances it isn't possible to switch/rebase branches,

Further the whole folder 'traffic_light_arduino\Release' is a majorly platform dependant result and therefore should not be present in the repository.

**Comment by BeckmaR** [comment]
Done with commits 13057e935de269e9f434a147f71ecb60ba05e180 and 14e3bff79322d495703a3353ee97072a65a918ac
