### ISSUE TITLE
example descriptions in SCT: no link hovering; no obvious way to access previous webpage after clicking on url

### ISSUE THREAD

**Issue by tangele** [Yakindu/examples#106]
Some of the example descriptions contain external links, similar to `Click *here* for additional information`
 
* no link hovering is available there. That means, the user cannot figure out if that link contains potential interesting information without actually visiting the url.
* after clicking on such an url,  its not obvious for some users, that you can go to the original page by pressing backspace.

Therefore, it might make sense to open such an url by default in the default webbrowser of the system. When we cannot do that, we should remove those external links and just write the URL out.

**Comment by tkutz** [comment]
With https://github.com/Yakindu/statecharts/pull/2829 all links will be opened in an external browser.

**Comment by tkutz** [comment]
Closed issue, because external links are opened in external browser now.
