### ISSUE TITLE
Improve description texts

### ISSUE THREAD

**Issue by tangele** [Yakindu/examples#107]
Following aspects can be checked:
- [x] update screenshots to have pinned def section, syntax highlighting and proper resolution
- [x] add short abstract to highlight what this example is demonstrating (similar to the getting started examples)
- [x] check if we can improve some styling issues (make things look nicer)

**Comment by tkutz** [comment]
See also https://github.com/Yakindu/examples/issues/110

**Comment by rherrmannr** [comment]
i think we have updated most parts
