### ISSUE TITLE
improve trafficlight cpp example

### ISSUE THREAD

**Issue by tangele** [Yakindu/examples#155]
https://github.com/Yakindu/examples/tree/master/org.yakindu.sct.examples.trafficlight.cpp

* make path consistent with project name
* index.html should contain explanations for QT.
* metadata.json should also contain notes about QT.
* improve index.html what the purpose of this example is
    * cpp code + c code generator

**Comment by tkutz** [comment]
We removed that example in favor of the already existing Qt/C++ example.
