### ISSUE TITLE
Basic Tutorial needs some polish

### ISSUE THREAD

**Issue by Mazesch** [Yakindu/examples#217]
* When installing the basic tutorial some classes have error markers on them
* The packages that are defined in the .sgen file are not in line with a newly generated .sgen file -> the user has to specify the location themselves or the files get generated to a place that is not the same as the other generated files, which might not be in tune with the idea of the 5-minute tutorial

**Comment by tkutz** [comment]
This should be already fixed on the master branch. You can switch the branch in the preferences for testing. The master branch will then be changed to the release4 branch once we release the product.
