### ISSUE TITLE
Additional metadata for examples

### ISSUE THREAD

**Issue by RainerKlute** [Yakindu/examples#24]
Examples should define additional optional metadata, like author, organization, version, license etc.

**Comment by BeckmaR** [comment]
This belongs in Yakindu/statecharts, doesn't it?

**Comment by RainerKlute** [comment]
No, it doesn't. But you don't have to work on it right now; it's just a reminder for a later point in time.

**Comment by rherrmannr** [comment]
reopen if this is still needed
