### ISSUE TITLE
Document last stage of the light switch example

### ISSUE THREAD

**Issue by RainerKlute** [Yakindu/examples#30]

**Comment by BeckmaR** [comment]
Done with 94c52e1

**Comment by RainerKlute** [comment]
Reopened for QA.

**Comment by RainerKlute** [comment]
@BeckmaR, please explain that stage more elaborately so the user can understand *what* the model does and *how*. Emphasis should be put on some newly-introduced features:
* Orthogonal substates
* `every` clause in the declaration section
* `raise` clause
And you should answer the question what the user could do to (sort of) simulate this example.

**Comment by BeckmaR** [comment]
I actually think all this belongs in the real documentation and not in the quick doc of the example whose scope is to inform the user about what to expect from this example. Writing this down here produces redundancies and scattered information.

**Comment by RainerKlute** [comment]
The reader should at least be able to understand how the example works. The example should describe what is happening in the model and why, without repeating the documentation in all its glory. To put it differently, while the document describes the concepts, the examples demonstrate how these concepts are **applied**.

Take the orthogonal regions: The reader should at least learn from the example description that those regions are executed in parallel and that they are called "orthogonal regions" or "orthogonal substates" so he could look up that concept in the SCT documentation.

Please have a look at how I described the other stages of this example.

**Comment by BeckmaR** [comment]
c10cb1e
