### ISSUE TITLE
CSS for header numbers in examples seems to be broken

### ISSUE THREAD

**Issue by BeckmaR** [Yakindu/examples#63]
Or maybe it counts in binary? ;) 

![image](https://cloud.githubusercontent.com/assets/15799654/24650533/c7c846a2-192a-11e7-80e3-b8e137b62a49.png)

**Comment by RainerKlute** [comment]
Generally it helps to not leave out any levels in the header hierarchy. In this case an H1 header was followed by an H3 header, leaving out the H2.

Anyway, I updated the example repository's CSS to the YAKINDU standard – and fixed the headers, see pull request #67.
