### ISSUE TITLE
[SCXML_Example] genmodel does not know statechart

### ISSUE THREAD

**Issue by svenjawendler** [Yakindu/examples#91]
![couldntresolvereference](https://user-images.githubusercontent.com/22005752/33992481-120f41d2-e0d3-11e7-8e06-ef99401c3072.png)

**Comment by svenjawendler** [comment]
Problem is: the project is imported as Java project. It needs to be an Xtext-project. When I add the Xtext nature the problem vanishes.

**Comment by andreasmuelder** [comment]
seems to be fixed
